CHAT_BOT_TYPE = "CHAT_BOT_TYPE"
USER_MESSAGE_TYPE = "USER_MESSAGE_TYPE"
SYSTEM_MESSAGE_TYPE = "SYSTEM_MESSAGE_TYPE"


OPERATION_TYPE = [
    (CHAT_BOT_TYPE, "Assistant"),
    (USER_MESSAGE_TYPE, "User"),
    (SYSTEM_MESSAGE_TYPE, "System"),
]

TEXT_TYPE = "TEXT_TYPE"
IMAGE_TYPE = "IMAGE_TYPE"
CODE_TYPE = "CODE_TYPE"


MESSAGE_TYPE = [
    (TEXT_TYPE, "Text"),
    (IMAGE_TYPE, "Image"),
    (CODE_TYPE, "Code"),
]

TITLES = [
    "Hành Trình Vượt Qua Sóng Gió",
    "Bí Ẩn Đại Dương Sâu",
    "Cuộc Sống Đơn Giản",
    "Nghệ Thuật Sống Chậm",
    "Những Người Bạn Tốt",
    "Tình Yêu Thương Mến",
    "Hành Trình Tìm Kiếm Hạnh Phúc",
    "Chìa Khóa Thành Công",
    "Khám Phá Thế Giới Mới",
    "Thắp Sáng Tương Lai",
    "Ngôi Nhà Bình Yên",
    "Những Ngày Xanh Tươi",
    "Giấc Mơ Đêm Hè",
    "Bước Chân Khám Phá",
    "Con Đường Không Tên",
    "Lòng Kiên Nhẫn Vô Biên",
    "Bí Mật Của Sự Bình Yên",
    "Những Khoảnh Khắc Đáng Nhớ",
    "Câu Chuyện Về Một Người",
    "Hương Vị Tình Yêu",
    "Tình Bạn Khác Thường",
    "Người Hùng Thầm Lặng",
    "Vùng Đất Bí Ẩn",
    "Điều Kỳ Diệu Trong Cuộc Sống",
    "Hành Trình Của Những Giấc Mơ",
    "Bài Học Từ Thất Bại",
    "Cuộc Sống Qua Lăng Kính",
    "Những Ngày Bình Dị",
    "Khám Phá Bản Thân",
    "Nụ Cười Của Mặt Trời",
    "Vượt Qua Thử Thách",
    "Bí Ẩn Cuộc Sống",
    "Giấc Mơ Tuổi Trẻ",
    "Đường Đời Lắm Nẻo",
    "Hành Trình Khám Phá Chính Mình",
    "Tình Yêu Trong Cơn Bão",
    "Những Ngày Tháng Thanh Xuân",
    "Chinh Phục Ước Mơ",
    "Nghệ Thuật Sống Tích Cực",
    "Bản Giao Hưởng Cuộc Đời",
    "Điều Kỳ Diệu Trong Tình Yêu",
    "Những Ngày Mưa Rào",
    "Khám Phá Bí Ẩn Thiên Nhiên",
    "Bước Qua Bóng Tối",
    "Vòng Tay Ấm Áp",
    "Giấc Mơ Khôn Lớn",
    "Nụ Hôn Đầu Tiên",
    "Chuyến Đi Của Đời Người",
    "Ánh Nắng Mặt Trời",
    "Khám Phá Tâm Hồn",
    "Hương Vị Cuộc Sống",
    "Tình Bạn Vĩnh Cửu",
    "Người Hùng Trong Bóng Tối",
    "Cuộc Sống Không Ngừng Chuyển Động",
    "Những Ngày Cuối Hạ",
    "Nghệ Thuật Sống Khỏe",
    "Vượt Qua Giông Bão",
    "Chuyến Tàu Ký Ức",
    "Những Giây Phút Đáng Nhớ",
    "Khám Phá Vũ Trụ",
    "Bí Ẩn Đêm Đen",
    "Hành Trình Yêu Thương",
    "Những Ngày Bình Yên",
    "Giấc Mơ Mùa Thu",
    "Tình Yêu Dưới Ánh Trăng",
    "Bước Chân Trên Cát",
    "Cuộc Sống Và Những Người Bạn",
    "Những Ngày Đẹp Trời",
    "Hành Trình Của Những Ước Mơ",
    "Bí Mật Tình Yêu",
    "Ngọn Lửa Tình Yêu",
    "Những Điều Kỳ Diệu",
    "Chuyện Tình Đầu Đời",
    "Nghệ Thuật Sống Hạnh Phúc",
    "Chuyến Đi Của Những Ước Mơ",
    "Vòng Tay Tình Bạn",
    "Giấc Mơ Trong Mưa",
    "Những Ngày Thu Vàng",
    "Khám Phá Thế Giới Bên Trong",
    "Tình Yêu Đầu Tiên",
    "Những Khoảnh Khắc Hạnh Phúc",
    "Cuộc Sống Trong Ánh Sáng",
    "Hành Trình Tìm Kiếm Bản Thân",
    "Bí Ẩn Trong Tim",
    "Chuyến Bay Vào Tương Lai",
    "Những Ngày Hè Rực Rỡ",
    "Nụ Cười Trong Gió",
    "Tình Yêu Và Hy Vọng",
    "Vùng Đất Mới",
    "Khám Phá Tình Yêu",
    "Những Ngày Nắng Vàng",
    "Giấc Mơ Xanh",
    "Chuyến Đi Của Sự Trưởng Thành",
    "Tình Yêu Trong Tim",
    "Nghệ Thuật Sống Đơn Giản",
    "Cuộc Sống Và Tình Yêu",
    "Bí Ẩn Của Sự Bình An",
    "Những Giấc Mơ Ngọt Ngào",
    "Hành Trình Của Những Người Bạn",
]
